apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  params:
    - name: app-name
      value: counter-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/counter-app:latest
    - name: git-url
      value: https://github.com/mdhabibi/ci-cd-final-project.git
    - name: git-revision
      value: main
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc

